Repository prgrms-web-devcourse-final-project/WEB2_3_Our-Tuft_BE, pull requests merged in 2025-02, with the labels that each got.

#8 Feat/#81 be 초기 프로젝트 환경 설정 및 필수 라이브러리 설치
  build.gradle
  src/main/java/com/example/web2_3_ourtuft_be/Web23OurTuftBeApplication.java
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/common/BaseTime.java
  src/main/java/com/example/web2_3_ourtuft_be/config/SwaggerConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/AccessDeniedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/DuplicatedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/GlobalException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/NotFoundException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/UnauthorizedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/AccessDeniedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/DuplicatedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/NotFoundMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/UnauthorizedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/response/GlobalResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/User.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/enums/Role.java
  src/main/java/com/example/web2_3_ourtuft_be/user/repository/UserRepository.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/web2_3_ourtuft_be/Web23OurTuftBeApplicationTests.java
Labels: feature

#10 feat: 마이페이지 조회#139
  .gitignore
  build.gradle
  src/main/java/com/example/web2_3_ourtuft_be/Web23OurTuftBeApplication.java
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/common/BaseTime.java
  src/main/java/com/example/web2_3_ourtuft_be/config/SwaggerConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/AccessDeniedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/DuplicatedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/GlobalException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/NotFoundException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/exceptions/UnauthorizedException.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/AccessDeniedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/DuplicatedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/NotFoundMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/UnauthorizedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/response/GlobalResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/main/java/com/example/web2_3_ourtuft_be/user/dto/ItemImageUrlDto.java
  src/main/java/com/example/web2_3_ourtuft_be/user/dto/NickNameColorItemDto.java
  src/main/java/com/example/web2_3_ourtuft_be/user/dto/UserProfileResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/MemberProfile.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/User.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/enums/Role.java
  src/main/java/com/example/web2_3_ourtuft_be/user/repository/MemberProfileRepository.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/web2_3_ourtuft_be/Web23OurTuftBeApplicationTests.java
Labels: feature

#22 ✨ Feature #93 : OAuth2.0 + Jwt
  build.gradle
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/auth/service/AuthService.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/RedisConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/SecurityConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/SwaggerConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/AccessDeniedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/response/GlobalResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/security/filter/CustomRequestFilter.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomAuthenticationEntrypoint.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomOAuthFailureHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/userdetails/UserDetailsImpl.java
  src/main/java/com/example/web2_3_ourtuft_be/security/util/JwtUtil.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/main/java/com/example/web2_3_ourtuft_be/user/dto/UserResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/User.java
  src/main/resources/application.yml
Labels: feature

#25 🪛 Fix #61 : 레포지토리 메서드 명 수정 및 스웨거 Operation 보충
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/auth/service/AuthService.java
  src/main/java/com/example/web2_3_ourtuft_be/item/controller/ItemController.java
  src/main/java/com/example/web2_3_ourtuft_be/lobby/controller/lobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/lobby/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/quiz/entity/QuizSet.java
  src/main/java/com/example/web2_3_ourtuft_be/quiz/service/QuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/room/entity/Room.java
  src/main/java/com/example/web2_3_ourtuft_be/room/repository/RoomRepository.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/MemberPoint.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/MemberPointService.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/UserFacadeService.java
Labels: fix

#30 🔧 Refactor #187 : 스웨거 에러 명세 약식 추가
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/SwaggerConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/NotFoundMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/global/response/GlobalResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/item/controller/ItemController.java
  src/main/java/com/example/web2_3_ourtuft_be/lobby/controller/lobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/quiz/controller/QuizController.java
  src/main/java/com/example/web2_3_ourtuft_be/quiz/dto/QuizSetRequest.java
  src/main/java/com/example/web2_3_ourtuft_be/quiz/service/QuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/test/java/com/example/web2_3_ourtuft_be/quiz/service/QuizServiceTest.java
Labels: refactor
