Repository prgrms-web-devcourse-final-project/WEB2_3_Our-Tuft_BE, pull requests merged in 2025-03, with the labels that each got.

#51 ✨ Feature #206 : 로비, 방 웹소켓 연결 및 레디스 저장 구현
  src/main/java/com/example/web2_3_ourtuft_be/auth/controller/AuthController.java
  src/main/java/com/example/web2_3_ourtuft_be/auth/service/AuthService.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/SecurityConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/UnauthorizedMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/LobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/security/filter/CustomRequestFilter.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomOAuthFailureHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/util/JwtUtil.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/main/java/com/example/web2_3_ourtuft_be/user/dto/UserResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/Point.java
  src/main/java/com/example/web2_3_ourtuft_be/user/entity/User.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/config/WebSocketConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/dto/WebSocketResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/interceptor/StompChannelInterceptor.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/interceptor/WebsocketHandshakeInterceptor.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: feature

#73 Fix : 웹소켓 관련 로직 1차 정리 및 추가
  src/main/java/com/example/web2_3_ourtuft_be/auth/dto/CustomOAuth2User.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/RedisConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/global/config/SwaggerConfig.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/RoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/security/filter/CustomRequestFilter.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomAuthenticationEntrypoint.java
  src/main/java/com/example/web2_3_ourtuft_be/security/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/example/web2_3_ourtuft_be/security/userdetails/UserDetailsImpl.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSGameController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSRoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/dto/WebSocketResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix

#74 Fix/key 메서드 수정
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/ParticipantService.java
  src/main/java/com/example/web2_3_ourtuft_be/security/util/JwtUtil.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
Labels: fix

#72 Feat: 문제 일정 주기로 내기, 웹소켓 service
  src/main/java/com/example/web2_3_ourtuft_be/game/controller/GameController.java
  src/main/java/com/example/web2_3_ourtuft_be/game/service/GameService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomQuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/entity/Room.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: feature

#75 update: 남은 참가자수 확인 함수 변경
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/ParticipantService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/security/filter/CustomRequestFilter.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/dto/WebSocketResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
Labels: fix

#80 feat: 대기실 정보 불러오기
  src/main/java/com/example/web2_3_ourtuft_be/global/exception/messages/BadRequestMessages.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/LobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomDetailResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
Labels: feature

#82 Fix : 이벤트 리스너 구독 퇴장
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/LobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/RoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
  src/main/resources/application.yml
Labels: fix

#87 퀴즈 캐싱 로직
  src/main/java/com/example/web2_3_ourtuft_be/game/controller/GameController.java
  src/main/java/com/example/web2_3_ourtuft_be/game/service/GameService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/controller/ParticipantController.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/ParticipantService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomQuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/LobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/RoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSGameController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix

#92 Fix/ 게임 로직
  src/main/java/com/example/web2_3_ourtuft_be/game/controller/GameController.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/ParticipantService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomQuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomSettingService.java
  src/main/java/com/example/web2_3_ourtuft_be/user/controller/UserController.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/MemberProfileService.java
  src/main/java/com/example/web2_3_ourtuft_be/user/service/UserFacadeService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSGameController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix

#93 Fix/ 타입 변경
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WebSocketController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix

#94 feat: OX 제출
  src/main/java/com/example/web2_3_ourtuft_be/game/controller/GameController.java
  src/main/java/com/example/web2_3_ourtuft_be/game/dto/OXResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/game/dto/OXSubmitRequestDto.java
  src/main/java/com/example/web2_3_ourtuft_be/game/service/OXQuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomQuizService.java
Labels: feature

#96 퀴즈 웹소켓 주기 전송 구현
  src/main/java/com/example/web2_3_ourtuft_be/global/initializer/ItemInitializer.java
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomQuizService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/RoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/RoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSGameController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSRoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: feature, fix

#97 Fix/ 로직 수정
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomResponseDto.java
Labels: fix

#102 🪛 FIX : 이동 간 방 삭제 로직 수정
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix

#103 ✨Feature : 점수 호출 API
  src/main/java/com/example/web2_3_ourtuft_be/game/controller/GameController.java
  src/main/java/com/example/web2_3_ourtuft_be/game/dto/GameResponse.java
  src/main/java/com/example/web2_3_ourtuft_be/game/service/GameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/event/WSEventListener.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: feature

#105 🪛Fix : Flag 세팅 수정
  src/main/java/com/example/web2_3_ourtuft_be/websocket/controller/WSGameController.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
Labels: fix

#125 🪛Fix : 방의 현재 인원 추가
  src/main/java/com/example/web2_3_ourtuft_be/redis/service/RoomSettingService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/LobbyController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/controller/RoomController.java
  src/main/java/com/example/web2_3_ourtuft_be/room/dto/RoomResponseDto.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/LobbyService.java
  src/main/java/com/example/web2_3_ourtuft_be/room/service/RoomService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/test/java/com/example/web2_3_ourtuft_be/lobby/service/LobbyServiceTest.java
Labels: fix

#132 🪛Fix : Flag 초기화 로직 수정
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WSGameService.java
  src/main/java/com/example/web2_3_ourtuft_be/websocket/service/WebSocketService.java
Labels: fix
